import '../models/food_item.dart';

class FoodDatabaseService {
  // 샘플 음식 데이터베이스
  static final List<FoodItem> _foodDatabase = [
    // 밥류
    FoodItem(
      id: 'food_001',
      name: '흰쌀밥',
      calories: 310,
      protein: 6,
      carbs: 68,
      fat: 0.5,
      servingSize: 210,
      unit: 'g',
      category: '밥류',
    ),
    FoodItem(
      id: 'food_002',
      name: '현미밥',
      calories: 280,
      protein: 6,
      carbs: 60,
      fat: 2,
      servingSize: 210,
      unit: 'g',
      category: '밥류',
    ),
    FoodItem(
      id: 'food_003',
      name: '김밥',
      calories: 450,
      protein: 12,
      carbs: 75,
      fat: 8,
      servingSize: 300,
      unit: 'g',
      category: '밥류',
    ),
    
    // 국/찌개류
    FoodItem(
      id: 'food_004',
      name: '된장찌개',
      calories: 150,
      protein: 10,
      carbs: 12,
      fat: 6,
      servingSize: 250,
      unit: 'ml',
      category: '국/찌개',
    ),
    FoodItem(
      id: 'food_005',
      name: '김치찌개',
      calories: 180,
      protein: 12,
      carbs: 10,
      fat: 8,
      servingSize: 250,
      unit: 'ml',
      category: '국/찌개',
    ),
    
    // 육류
    FoodItem(
      id: 'food_006',
      name: '닭가슴살',
      calories: 165,
      protein: 31,
      carbs: 0,
      fat: 3.6,
      servingSize: 100,
      unit: 'g',
      category: '육류',
    ),
    FoodItem(
      id: 'food_007',
      name: '삼겹살',
      calories: 518,
      protein: 17,
      carbs: 0,
      fat: 50,
      servingSize: 100,
      unit: 'g',
      category: '육류',
    ),
    FoodItem(
      id: 'food_008',
      name: '소고기(등심)',
      calories: 250,
      protein: 20,
      carbs: 0,
      fat: 18,
      servingSize: 100,
      unit: 'g',
      category: '육류',
    ),
    
    // 생선
    FoodItem(
      id: 'food_009',
      name: '고등어구이',
      calories: 262,
      protein: 22,
      carbs: 0,
      fat: 19,
      servingSize: 100,
      unit: 'g',
      category: '생선',
    ),
    FoodItem(
      id: 'food_010',
      name: '연어',
      calories: 208,
      protein: 20,
      carbs: 0,
      fat: 13,
      servingSize: 100,
      unit: 'g',
      category: '생선',
    ),
    
    // 채소
    FoodItem(
      id: 'food_011',
      name: '시금치나물',
      calories: 35,
      protein: 3,
      carbs: 4,
      fat: 1,
      servingSize: 100,
      unit: 'g',
      category: '채소',
    ),
    FoodItem(
      id: 'food_012',
      name: '배추김치',
      calories: 18,
      protein: 1,
      carbs: 3,
      fat: 0.2,
      servingSize: 100,
      unit: 'g',
      category: '채소',
    ),
    
    // 빵/과자
    FoodItem(
      id: 'food_013',
      name: '식빵',
      calories: 270,
      protein: 8,
      carbs: 50,
      fat: 4,
      servingSize: 100,
      unit: 'g',
      category: '빵/과자',
    ),
    FoodItem(
      id: 'food_014',
      name: '크로와상',
      calories: 406,
      protein: 8,
      carbs: 46,
      fat: 21,
      servingSize: 100,
      unit: 'g',
      category: '빵/과자',
    ),
    
    // 음료
    FoodItem(
      id: 'food_015',
      name: '아메리카노',
      calories: 5,
      protein: 0.3,
      carbs: 1,
      fat: 0,
      servingSize: 240,
      unit: 'ml',
      category: '음료',
    ),
    FoodItem(
      id: 'food_016',
      name: '카페라떼',
      calories: 150,
      protein: 8,
      carbs: 15,
      fat: 6,
      servingSize: 240,
      unit: 'ml',
      category: '음료',
    ),
    FoodItem(
      id: 'food_017',
      name: '콜라',
      calories: 42,
      protein: 0,
      carbs: 10.6,
      fat: 0,
      servingSize: 100,
      unit: 'ml',
      category: '음료',
    ),
    
    // 과일
    FoodItem(
      id: 'food_018',
      name: '사과',
      calories: 52,
      protein: 0.3,
      carbs: 14,
      fat: 0.2,
      servingSize: 100,
      unit: 'g',
      category: '과일',
    ),
    FoodItem(
      id: 'food_019',
      name: '바나나',
      calories: 89,
      protein: 1.1,
      carbs: 23,
      fat: 0.3,
      servingSize: 100,
      unit: 'g',
      category: '과일',
    ),
    
    // 면류
    FoodItem(
      id: 'food_020',
      name: '라면',
      calories: 510,
      protein: 10,
      carbs: 80,
      fat: 16,
      servingSize: 120,
      unit: 'g',
      category: '면류',
    ),
    FoodItem(
      id: 'food_021',
      name: '짜장면',
      calories: 580,
      protein: 18,
      carbs: 95,
      fat: 12,
      servingSize: 400,
      unit: 'g',
      category: '면류',
    ),

    // ========================================
    // 학식 메뉴 (November 2025 Weekly Meal Plans)
    // ========================================

    // Week 1: November 3-9, 2025
    // Monday Nov 3
    FoodItem(
      id: 'cafeteria_001',
      name: '떡국',
      calories: 380,
      protein: 15,
      carbs: 55,
      fat: 10,
      servingSize: 350,
      unit: 'g',
      category: '학식-조식',
    ),
    FoodItem(
      id: 'cafeteria_002',
      name: '돈까스',
      calories: 520,
      protein: 25,
      carbs: 45,
      fat: 25,
      servingSize: 300,
      unit: 'g',
      category: '학식-중식',
    ),
    FoodItem(
      id: 'cafeteria_003',
      name: '불고기버섯전골',
      calories: 450,
      protein: 28,
      carbs: 35,
      fat: 22,
      servingSize: 400,
      unit: 'g',
      category: '학식-석식',
    ),
    // Tuesday Nov 4
    FoodItem(
      id: 'cafeteria_004',
      name: '어묵국',
      calories: 280,
      protein: 12,
      carbs: 40,
      fat: 8,
      servingSize: 350,
      unit: 'g',
      category: '학식-조식',
    ),
    FoodItem(
      id: 'cafeteria_005',
      name: '닭볶음탕',
      calories: 480,
      protein: 32,
      carbs: 30,
      fat: 24,
      servingSize: 350,
      unit: 'g',
      category: '학식-중식',
    ),
    FoodItem(
      id: 'cafeteria_006',
      name: '낙지비빔밥',
      calories: 520,
      protein: 22,
      carbs: 65,
      fat: 18,
      servingSize: 400,
      unit: 'g',
      category: '학식-석식',
    ),
    // Wednesday Nov 5
    FoodItem(
      id: 'cafeteria_007',
      name: '된장국',
      calories: 180,
      protein: 10,
      carbs: 20,
      fat: 6,
      servingSize: 300,
      unit: 'g',
      category: '학식-조식',
    ),
    FoodItem(
      id: 'cafeteria_008',
      name: '제육볶음',
      calories: 480,
      protein: 25,
      carbs: 40,
      fat: 25,
      servingSize: 300,
      unit: 'g',
      category: '학식-중식',
    ),
    FoodItem(
      id: 'cafeteria_009',
      name: '카레라이스',
      calories: 550,
      protein: 18,
      carbs: 75,
      fat: 20,
      servingSize: 400,
      unit: 'g',
      category: '학식-석식',
    ),
    // Thursday Nov 6
    FoodItem(
      id: 'cafeteria_010',
      name: '북어국',
      calories: 200,
      protein: 18,
      carbs: 15,
      fat: 6,
      servingSize: 350,
      unit: 'g',
      category: '학식-조식',
    ),
    FoodItem(
      id: 'cafeteria_011',
      name: '소불고기',
      calories: 420,
      protein: 28,
      carbs: 30,
      fat: 22,
      servingSize: 280,
      unit: 'g',
      category: '학식-중식',
    ),
    FoodItem(
      id: 'cafeteria_012',
      name: '김치볶음밥',
      calories: 480,
      protein: 15,
      carbs: 70,
      fat: 15,
      servingSize: 350,
      unit: 'g',
      category: '학식-석식',
    ),
    // Friday Nov 7
    FoodItem(
      id: 'cafeteria_013',
      name: '미역국',
      calories: 150,
      protein: 8,
      carbs: 12,
      fat: 8,
      servingSize: 300,
      unit: 'g',
      category: '학식-조식',
    ),
    FoodItem(
      id: 'cafeteria_014',
      name: '치킨마요덮밥',
      calories: 620,
      protein: 28,
      carbs: 70,
      fat: 25,
      servingSize: 400,
      unit: 'g',
      category: '학식-중식',
    ),
    FoodItem(
      id: 'cafeteria_015',
      name: '순두부찌개',
      calories: 320,
      protein: 18,
      carbs: 20,
      fat: 18,
      servingSize: 350,
      unit: 'g',
      category: '학식-석식',
    ),

    // Week 2: November 10-16, 2025
    // Monday Nov 10
    FoodItem(
      id: 'cafeteria_016',
      name: '새우완탕',
      calories: 350,
      protein: 15,
      carbs: 45,
      fat: 12,
      servingSize: 350,
      unit: 'g',
      category: '학식-조식',
    ),
    FoodItem(
      id: 'cafeteria_017',
      name: '돼지김치비빔밥',
      calories: 550,
      protein: 22,
      carbs: 68,
      fat: 20,
      servingSize: 400,
      unit: 'g',
      category: '학식-중식',
    ),
    FoodItem(
      id: 'cafeteria_018',
      name: '갈비비빔밥',
      calories: 580,
      protein: 28,
      carbs: 65,
      fat: 22,
      servingSize: 400,
      unit: 'g',
      category: '학식-석식',
    ),
    // Tuesday Nov 11
    FoodItem(
      id: 'cafeteria_019',
      name: '콩나물국',
      calories: 160,
      protein: 8,
      carbs: 18,
      fat: 5,
      servingSize: 300,
      unit: 'g',
      category: '학식-조식',
    ),
    FoodItem(
      id: 'cafeteria_020',
      name: '등심돈까스',
      calories: 550,
      protein: 28,
      carbs: 48,
      fat: 28,
      servingSize: 320,
      unit: 'g',
      category: '학식-중식',
    ),
    FoodItem(
      id: 'cafeteria_021',
      name: '짬뽕',
      calories: 520,
      protein: 20,
      carbs: 60,
      fat: 22,
      servingSize: 450,
      unit: 'g',
      category: '학식-석식',
    ),
    // Wednesday Nov 12
    FoodItem(
      id: 'cafeteria_022',
      name: '계란국',
      calories: 180,
      protein: 12,
      carbs: 10,
      fat: 10,
      servingSize: 300,
      unit: 'g',
      category: '학식-조식',
    ),
    FoodItem(
      id: 'cafeteria_023',
      name: '오징어덮밥',
      calories: 480,
      protein: 22,
      carbs: 62,
      fat: 15,
      servingSize: 380,
      unit: 'g',
      category: '학식-중식',
    ),
    FoodItem(
      id: 'cafeteria_024',
      name: '부대찌개',
      calories: 450,
      protein: 20,
      carbs: 40,
      fat: 24,
      servingSize: 400,
      unit: 'g',
      category: '학식-석식',
    ),
    // Thursday Nov 13
    FoodItem(
      id: 'cafeteria_025',
      name: '시래기국',
      calories: 170,
      protein: 10,
      carbs: 20,
      fat: 6,
      servingSize: 300,
      unit: 'g',
      category: '학식-조식',
    ),
    FoodItem(
      id: 'cafeteria_026',
      name: '햄버그스테이크',
      calories: 520,
      protein: 28,
      carbs: 35,
      fat: 30,
      servingSize: 300,
      unit: 'g',
      category: '학식-중식',
    ),
    FoodItem(
      id: 'cafeteria_027',
      name: '된장찌개정식',
      calories: 420,
      protein: 18,
      carbs: 50,
      fat: 16,
      servingSize: 380,
      unit: 'g',
      category: '학식-석식',
    ),
    // Friday Nov 14
    FoodItem(
      id: 'cafeteria_028',
      name: '소고기무국',
      calories: 220,
      protein: 15,
      carbs: 18,
      fat: 10,
      servingSize: 350,
      unit: 'g',
      category: '학식-조식',
    ),
    FoodItem(
      id: 'cafeteria_029',
      name: '쭈꾸미볶음',
      calories: 380,
      protein: 25,
      carbs: 28,
      fat: 18,
      servingSize: 280,
      unit: 'g',
      category: '학식-중식',
    ),
    FoodItem(
      id: 'cafeteria_030',
      name: '해물칼국수',
      calories: 420,
      protein: 18,
      carbs: 58,
      fat: 12,
      servingSize: 450,
      unit: 'g',
      category: '학식-석식',
    ),

    // Week 3: November 17-23, 2025
    // Monday Nov 17
    FoodItem(
      id: 'cafeteria_031',
      name: '우동',
      calories: 380,
      protein: 12,
      carbs: 55,
      fat: 12,
      servingSize: 400,
      unit: 'g',
      category: '학식-조식',
    ),
    FoodItem(
      id: 'cafeteria_032',
      name: '매운갈비찜',
      calories: 550,
      protein: 32,
      carbs: 35,
      fat: 30,
      servingSize: 350,
      unit: 'g',
      category: '학식-중식',
    ),
    FoodItem(
      id: 'cafeteria_033',
      name: '닭곰탕',
      calories: 380,
      protein: 28,
      carbs: 25,
      fat: 18,
      servingSize: 400,
      unit: 'g',
      category: '학식-석식',
    ),
    // Tuesday Nov 18
    FoodItem(
      id: 'cafeteria_034',
      name: '김치수제비',
      calories: 350,
      protein: 10,
      carbs: 55,
      fat: 10,
      servingSize: 400,
      unit: 'g',
      category: '학식-조식',
    ),
    FoodItem(
      id: 'cafeteria_035',
      name: '순살치킨',
      calories: 520,
      protein: 35,
      carbs: 30,
      fat: 28,
      servingSize: 280,
      unit: 'g',
      category: '학식-중식',
    ),
    FoodItem(
      id: 'cafeteria_036',
      name: '비빔냉면',
      calories: 480,
      protein: 15,
      carbs: 70,
      fat: 15,
      servingSize: 450,
      unit: 'g',
      category: '학식-석식',
    ),
    // Wednesday Nov 19
    FoodItem(
      id: 'cafeteria_037',
      name: '라면',
      calories: 510,
      protein: 10,
      carbs: 80,
      fat: 16,
      servingSize: 450,
      unit: 'g',
      category: '학식-조식',
    ),
    FoodItem(
      id: 'cafeteria_038',
      name: '돼지갈비',
      calories: 580,
      protein: 30,
      carbs: 25,
      fat: 40,
      servingSize: 300,
      unit: 'g',
      category: '학식-중식',
    ),
    FoodItem(
      id: 'cafeteria_039',
      name: '콩국수',
      calories: 420,
      protein: 18,
      carbs: 50,
      fat: 18,
      servingSize: 450,
      unit: 'g',
      category: '학식-석식',
    ),
    // Thursday Nov 20
    FoodItem(
      id: 'cafeteria_040',
      name: '황태국',
      calories: 180,
      protein: 20,
      carbs: 10,
      fat: 6,
      servingSize: 350,
      unit: 'g',
      category: '학식-조식',
    ),
    FoodItem(
      id: 'cafeteria_041',
      name: '쌈밥정식',
      calories: 520,
      protein: 25,
      carbs: 60,
      fat: 20,
      servingSize: 400,
      unit: 'g',
      category: '학식-중식',
    ),
    FoodItem(
      id: 'cafeteria_042',
      name: '청국장찌개',
      calories: 350,
      protein: 18,
      carbs: 30,
      fat: 18,
      servingSize: 350,
      unit: 'g',
      category: '학식-석식',
    ),
    // Friday Nov 21
    FoodItem(
      id: 'cafeteria_043',
      name: '만두국',
      calories: 380,
      protein: 15,
      carbs: 50,
      fat: 12,
      servingSize: 400,
      unit: 'g',
      category: '학식-조식',
    ),
    FoodItem(
      id: 'cafeteria_044',
      name: '탕수육',
      calories: 550,
      protein: 22,
      carbs: 55,
      fat: 28,
      servingSize: 300,
      unit: 'g',
      category: '학식-중식',
    ),
    FoodItem(
      id: 'cafeteria_045',
      name: '샤브샤브',
      calories: 380,
      protein: 25,
      carbs: 30,
      fat: 18,
      servingSize: 450,
      unit: 'g',
      category: '학식-석식',
    ),

    // Week 4: November 24-30, 2025
    // Monday Nov 24
    FoodItem(
      id: 'cafeteria_046',
      name: '소시지스튜',
      calories: 420,
      protein: 18,
      carbs: 40,
      fat: 22,
      servingSize: 350,
      unit: 'g',
      category: '학식-조식',
    ),
    FoodItem(
      id: 'cafeteria_047',
      name: '마라소고기볶음',
      calories: 520,
      protein: 28,
      carbs: 35,
      fat: 30,
      servingSize: 320,
      unit: 'g',
      category: '학식-중식',
    ),
    FoodItem(
      id: 'cafeteria_048',
      name: '양배추스튜',
      calories: 280,
      protein: 12,
      carbs: 35,
      fat: 10,
      servingSize: 350,
      unit: 'g',
      category: '학식-석식',
    ),
    // Tuesday Nov 25
    FoodItem(
      id: 'cafeteria_049',
      name: '닭죽',
      calories: 280,
      protein: 15,
      carbs: 40,
      fat: 6,
      servingSize: 350,
      unit: 'g',
      category: '학식-조식',
    ),
    FoodItem(
      id: 'cafeteria_050',
      name: '매콤닭갈비',
      calories: 480,
      protein: 30,
      carbs: 35,
      fat: 24,
      servingSize: 320,
      unit: 'g',
      category: '학식-중식',
    ),
    FoodItem(
      id: 'cafeteria_051',
      name: '해물파전',
      calories: 380,
      protein: 15,
      carbs: 45,
      fat: 16,
      servingSize: 250,
      unit: 'g',
      category: '학식-석식',
    ),
    // Wednesday Nov 26
    FoodItem(
      id: 'cafeteria_052',
      name: '참치김밥',
      calories: 420,
      protein: 18,
      carbs: 60,
      fat: 12,
      servingSize: 280,
      unit: 'g',
      category: '학식-조식',
    ),
    FoodItem(
      id: 'cafeteria_053',
      name: '찜닭',
      calories: 520,
      protein: 32,
      carbs: 40,
      fat: 26,
      servingSize: 350,
      unit: 'g',
      category: '학식-중식',
    ),
    FoodItem(
      id: 'cafeteria_054',
      name: '물냉면',
      calories: 450,
      protein: 12,
      carbs: 75,
      fat: 10,
      servingSize: 500,
      unit: 'g',
      category: '학식-석식',
    ),
    // Thursday Nov 27
    FoodItem(
      id: 'cafeteria_055',
      name: '호박죽',
      calories: 220,
      protein: 5,
      carbs: 45,
      fat: 3,
      servingSize: 300,
      unit: 'g',
      category: '학식-조식',
    ),
    FoodItem(
      id: 'cafeteria_056',
      name: '갈비탕',
      calories: 480,
      protein: 28,
      carbs: 25,
      fat: 30,
      servingSize: 450,
      unit: 'g',
      category: '학식-중식',
    ),
    FoodItem(
      id: 'cafeteria_057',
      name: '오므라이스',
      calories: 520,
      protein: 20,
      carbs: 65,
      fat: 22,
      servingSize: 380,
      unit: 'g',
      category: '학식-석식',
    ),
    // Friday Nov 28
    FoodItem(
      id: 'cafeteria_058',
      name: '감자수프',
      calories: 250,
      protein: 8,
      carbs: 35,
      fat: 10,
      servingSize: 300,
      unit: 'g',
      category: '학식-조식',
    ),
    FoodItem(
      id: 'cafeteria_059',
      name: '불닭볶음면',
      calories: 580,
      protein: 15,
      carbs: 80,
      fat: 22,
      servingSize: 400,
      unit: 'g',
      category: '학식-중식',
    ),
    FoodItem(
      id: 'cafeteria_060',
      name: '육개장',
      calories: 350,
      protein: 22,
      carbs: 25,
      fat: 18,
      servingSize: 400,
      unit: 'g',
      category: '학식-석식',
    ),
  ];

  // 모든 음식 가져오기
  static List<FoodItem> getAllFoods() {
    return _foodDatabase;
  }

  // 음식 검색
  static List<FoodItem> searchFoods(String query) {
    if (query.isEmpty) {
      return _foodDatabase;
    }
    
    return _foodDatabase.where((food) {
      return food.name.toLowerCase().contains(query.toLowerCase());
    }).toList();
  }

  // 카테고리별 음식 가져오기
  static List<FoodItem> getFoodsByCategory(String category) {
    return _foodDatabase.where((food) => food.category == category).toList();
  }

  // ID로 음식 찾기
  static FoodItem? getFoodById(String id) {
    try {
      return _foodDatabase.firstWhere((food) => food.id == id);
    } catch (e) {
      return null;
    }
  }

  // 음식 추가 (사용자 정의 음식)
  static void addFood(FoodItem food) {
    _foodDatabase.add(food);
  }

  // 모든 카테고리 가져오기
  static List<String> getAllCategories() {
    return _foodDatabase
        .map((food) => food.category ?? '기타')
        .toSet()
        .toList();
  }
}
