// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD7sPR6Fj3qazwD9ytw_ofBij0GzLmCHY',
    appId: '1:127024081899:web:13b8b17388b29c4852c7ae',
    messagingSenderId: '127024081899',
    projectId: 'device-streaming-2d5c0ef4',
    authDomain: 'device-streaming-2d5c0ef4.firebaseapp.com',
    storageBucket: 'device-streaming-2d5c0ef4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHta7DsLoQYUCQwLCI70HjMPJK5C5f4rY',
    appId: '1:127024081899:android:671ca50534b19ed952c7ae',
    messagingSenderId: '127024081899',
    projectId: 'device-streaming-2d5c0ef4',
    storageBucket: 'device-streaming-2d5c0ef4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDshdVnN7IB6V5PwOldbJsF-kjAxOhkCCw',
    appId: '1:127024081899:ios:4d0fd179c59e2a1f52c7ae',
    messagingSenderId: '127024081899',
    projectId: 'device-streaming-2d5c0ef4',
    storageBucket: 'device-streaming-2d5c0ef4.firebasestorage.app',
    iosBundleId: 'com.example.dietTrackingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDshdVnN7IB6V5PwOldbJsF-kjAxOhkCCw',
    appId: '1:127024081899:ios:4d0fd179c59e2a1f52c7ae',
    messagingSenderId: '127024081899',
    projectId: 'device-streaming-2d5c0ef4',
    storageBucket: 'device-streaming-2d5c0ef4.firebasestorage.app',
    iosBundleId: 'com.example.dietTrackingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCD7sPR6Fj3qazwD9ytw_ofBij0GzLmCHY',
    appId: '1:127024081899:web:6ec1367bb219920c52c7ae',
    messagingSenderId: '127024081899',
    projectId: 'device-streaming-2d5c0ef4',
    authDomain: 'device-streaming-2d5c0ef4.firebaseapp.com',
    storageBucket: 'device-streaming-2d5c0ef4.firebasestorage.app',
  );

}